services:
  - type: web
    name: medical-anonymizer
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python chat_app.py"
    envVars:
      - key: USE_LOCAL_DB
        value: true
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src
      sizeGB: 1
